// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResData.proto

package com.sgcc.bochao.ggt.manage.protobuf;

public final class ResData {
  private ResData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResSSSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ResSSS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> 
        getResList();
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getRes(int index);
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    int getResCount();
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    java.util.List<? extends com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder> 
        getResOrBuilderList();
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder getResOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.ResSSS}
   */
  public  static final class ResSSS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.ResSSS)
      ResSSSOrBuilder {
    // Use ResSSS.newBuilder() to construct.
    private ResSSS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResSSS() {
      res_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResSSS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                res_ = new java.util.ArrayList<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res>();
                mutable_bitField0_ |= 0x00000001;
              }
              res_.add(
                  input.readMessage(com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          res_ = java.util.Collections.unmodifiableList(res_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_ResSSS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_ResSSS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.class, com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.Builder.class);
    }

    public static final int RES_FIELD_NUMBER = 1;
    private java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> res_;
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    public java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> getResList() {
      return res_;
    }
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    public java.util.List<? extends com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder> 
        getResOrBuilderList() {
      return res_;
    }
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    public int getResCount() {
      return res_.size();
    }
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getRes(int index) {
      return res_.get(index);
    }
    /**
     * <code>repeated .protobuf.Res res = 1;</code>
     */
    public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder getResOrBuilder(
        int index) {
      return res_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < res_.size(); i++) {
        output.writeMessage(1, res_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < res_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, res_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS)) {
        return super.equals(obj);
      }
      com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS other = (com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS) obj;

      boolean result = true;
      result = result && getResList()
          .equals(other.getResList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getResCount() > 0) {
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + getResList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ResSSS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ResSSS)
        com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_ResSSS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_ResSSS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.class, com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.Builder.class);
      }

      // Construct using com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (resBuilder_ == null) {
          res_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_ResSSS_descriptor;
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS getDefaultInstanceForType() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.getDefaultInstance();
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS build() {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS buildPartial() {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS result = new com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS(this);
        int from_bitField0_ = bitField0_;
        if (resBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            res_ = java.util.Collections.unmodifiableList(res_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.res_ = res_;
        } else {
          result.res_ = resBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS) {
          return mergeFrom((com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS other) {
        if (other == com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS.getDefaultInstance()) return this;
        if (resBuilder_ == null) {
          if (!other.res_.isEmpty()) {
            if (res_.isEmpty()) {
              res_ = other.res_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResIsMutable();
              res_.addAll(other.res_);
            }
            onChanged();
          }
        } else {
          if (!other.res_.isEmpty()) {
            if (resBuilder_.isEmpty()) {
              resBuilder_.dispose();
              resBuilder_ = null;
              res_ = other.res_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResFieldBuilder() : null;
            } else {
              resBuilder_.addAllMessages(other.res_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> res_ =
        java.util.Collections.emptyList();
      private void ensureResIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          res_ = new java.util.ArrayList<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res>(res_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sgcc.bochao.ggt.manage.protobuf.ResData.Res, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder, com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder> resBuilder_;

      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> getResList() {
        if (resBuilder_ == null) {
          return java.util.Collections.unmodifiableList(res_);
        } else {
          return resBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public int getResCount() {
        if (resBuilder_ == null) {
          return res_.size();
        } else {
          return resBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getRes(int index) {
        if (resBuilder_ == null) {
          return res_.get(index);
        } else {
          return resBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder setRes(
          int index, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResIsMutable();
          res_.set(index, value);
          onChanged();
        } else {
          resBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder setRes(
          int index, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder builderForValue) {
        if (resBuilder_ == null) {
          ensureResIsMutable();
          res_.set(index, builderForValue.build());
          onChanged();
        } else {
          resBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder addRes(com.sgcc.bochao.ggt.manage.protobuf.ResData.Res value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResIsMutable();
          res_.add(value);
          onChanged();
        } else {
          resBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder addRes(
          int index, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResIsMutable();
          res_.add(index, value);
          onChanged();
        } else {
          resBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder addRes(
          com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder builderForValue) {
        if (resBuilder_ == null) {
          ensureResIsMutable();
          res_.add(builderForValue.build());
          onChanged();
        } else {
          resBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder addRes(
          int index, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder builderForValue) {
        if (resBuilder_ == null) {
          ensureResIsMutable();
          res_.add(index, builderForValue.build());
          onChanged();
        } else {
          resBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder addAllRes(
          java.lang.Iterable<? extends com.sgcc.bochao.ggt.manage.protobuf.ResData.Res> values) {
        if (resBuilder_ == null) {
          ensureResIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, res_);
          onChanged();
        } else {
          resBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder clearRes() {
        if (resBuilder_ == null) {
          res_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public Builder removeRes(int index) {
        if (resBuilder_ == null) {
          ensureResIsMutable();
          res_.remove(index);
          onChanged();
        } else {
          resBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder getResBuilder(
          int index) {
        return getResFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder getResOrBuilder(
          int index) {
        if (resBuilder_ == null) {
          return res_.get(index);  } else {
          return resBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public java.util.List<? extends com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder> 
           getResOrBuilderList() {
        if (resBuilder_ != null) {
          return resBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(res_);
        }
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder addResBuilder() {
        return getResFieldBuilder().addBuilder(
            com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder addResBuilder(
          int index) {
        return getResFieldBuilder().addBuilder(
            index, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Res res = 1;</code>
       */
      public java.util.List<com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder> 
           getResBuilderList() {
        return getResFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sgcc.bochao.ggt.manage.protobuf.ResData.Res, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder, com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder> 
          getResFieldBuilder() {
        if (resBuilder_ == null) {
          resBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sgcc.bochao.ggt.manage.protobuf.ResData.Res, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder, com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder>(
                  res_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          res_ = null;
        }
        return resBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.ResSSS)
    }

    // @@protoc_insertion_point(class_scope:protobuf.ResSSS)
    private static final com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS();
    }

    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResSSS>
        PARSER = new com.google.protobuf.AbstractParser<ResSSS>() {
      public ResSSS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResSSS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResSSS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResSSS> getParserForType() {
      return PARSER;
    }

    public com.sgcc.bochao.ggt.manage.protobuf.ResData.ResSSS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string ResType = 1;</code>
     */
    java.lang.String getResType();
    /**
     * <code>optional string ResType = 1;</code>
     */
    com.google.protobuf.ByteString
        getResTypeBytes();

    /**
     * <code>optional string ResName = 2;</code>
     */
    java.lang.String getResName();
    /**
     * <code>optional string ResName = 2;</code>
     */
    com.google.protobuf.ByteString
        getResNameBytes();

    /**
     * <code>optional string ResCost = 3;</code>
     */
    java.lang.String getResCost();
    /**
     * <code>optional string ResCost = 3;</code>
     */
    com.google.protobuf.ByteString
        getResCostBytes();

    /**
     * <code>optional string ResUnit = 4;</code>
     */
    java.lang.String getResUnit();
    /**
     * <code>optional string ResUnit = 4;</code>
     */
    com.google.protobuf.ByteString
        getResUnitBytes();

    /**
     * <code>optional string ResModelName = 5;</code>
     */
    java.lang.String getResModelName();
    /**
     * <code>optional string ResModelName = 5;</code>
     */
    com.google.protobuf.ByteString
        getResModelNameBytes();

    /**
     * <code>optional string ResPicName = 6;</code>
     */
    java.lang.String getResPicName();
    /**
     * <code>optional string ResPicName = 6;</code>
     */
    com.google.protobuf.ByteString
        getResPicNameBytes();

    /**
     * <code>optional string ResABName = 7;</code>
     */
    java.lang.String getResABName();
    /**
     * <code>optional string ResABName = 7;</code>
     */
    com.google.protobuf.ByteString
        getResABNameBytes();

    /**
     * <code>optional string ResSltABName = 8;</code>
     */
    java.lang.String getResSltABName();
    /**
     * <code>optional string ResSltABName = 8;</code>
     */
    com.google.protobuf.ByteString
        getResSltABNameBytes();

    /**
     * <code>optional string ResAddTime = 9;</code>
     */
    java.lang.String getResAddTime();
    /**
     * <code>optional string ResAddTime = 9;</code>
     */
    com.google.protobuf.ByteString
        getResAddTimeBytes();

    /**
     * <code>optional string ResAddMan = 10;</code>
     */
    java.lang.String getResAddMan();
    /**
     * <code>optional string ResAddMan = 10;</code>
     */
    com.google.protobuf.ByteString
        getResAddManBytes();

    /**
     * <code>optional string ResUpTime = 11;</code>
     */
    java.lang.String getResUpTime();
    /**
     * <code>optional string ResUpTime = 11;</code>
     */
    com.google.protobuf.ByteString
        getResUpTimeBytes();

    /**
     * <code>optional string ResUpMan = 12;</code>
     */
    java.lang.String getResUpMan();
    /**
     * <code>optional string ResUpMan = 12;</code>
     */
    com.google.protobuf.ByteString
        getResUpManBytes();

    /**
     * <code>optional bytes ResModel = 13;</code>
     */
    com.google.protobuf.ByteString getResModel();

    /**
     * <code>optional bytes ResPic = 14;</code>
     */
    com.google.protobuf.ByteString getResPic();

    /**
     * <code>optional string ResGuid = 15;</code>
     */
    java.lang.String getResGuid();
    /**
     * <code>optional string ResGuid = 15;</code>
     */
    com.google.protobuf.ByteString
        getResGuidBytes();
  }
  /**
   * Protobuf type {@code protobuf.Res}
   */
  public  static final class Res extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Res)
      ResOrBuilder {
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Res() {
      resType_ = "";
      resName_ = "";
      resCost_ = "";
      resUnit_ = "";
      resModelName_ = "";
      resPicName_ = "";
      resABName_ = "";
      resSltABName_ = "";
      resAddTime_ = "";
      resAddMan_ = "";
      resUpTime_ = "";
      resUpMan_ = "";
      resModel_ = com.google.protobuf.ByteString.EMPTY;
      resPic_ = com.google.protobuf.ByteString.EMPTY;
      resGuid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              resType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              resName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              resCost_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              resUnit_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              resModelName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              resPicName_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              resABName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              resSltABName_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              resAddTime_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              resAddMan_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              resUpTime_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              resUpMan_ = s;
              break;
            }
            case 106: {

              resModel_ = input.readBytes();
              break;
            }
            case 114: {

              resPic_ = input.readBytes();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              resGuid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_Res_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.class, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder.class);
    }

    public static final int RESTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object resType_;
    /**
     * <code>optional string ResType = 1;</code>
     */
    public java.lang.String getResType() {
      java.lang.Object ref = resType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResTypeBytes() {
      java.lang.Object ref = resType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object resName_;
    /**
     * <code>optional string ResName = 2;</code>
     */
    public java.lang.String getResName() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResNameBytes() {
      java.lang.Object ref = resName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESCOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object resCost_;
    /**
     * <code>optional string ResCost = 3;</code>
     */
    public java.lang.String getResCost() {
      java.lang.Object ref = resCost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resCost_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResCost = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResCostBytes() {
      java.lang.Object ref = resCost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resCost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESUNIT_FIELD_NUMBER = 4;
    private volatile java.lang.Object resUnit_;
    /**
     * <code>optional string ResUnit = 4;</code>
     */
    public java.lang.String getResUnit() {
      java.lang.Object ref = resUnit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resUnit_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResUnit = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResUnitBytes() {
      java.lang.Object ref = resUnit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESMODELNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object resModelName_;
    /**
     * <code>optional string ResModelName = 5;</code>
     */
    public java.lang.String getResModelName() {
      java.lang.Object ref = resModelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resModelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResModelName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getResModelNameBytes() {
      java.lang.Object ref = resModelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resModelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPICNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object resPicName_;
    /**
     * <code>optional string ResPicName = 6;</code>
     */
    public java.lang.String getResPicName() {
      java.lang.Object ref = resPicName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resPicName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResPicName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getResPicNameBytes() {
      java.lang.Object ref = resPicName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resPicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESABNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object resABName_;
    /**
     * <code>optional string ResABName = 7;</code>
     */
    public java.lang.String getResABName() {
      java.lang.Object ref = resABName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resABName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResABName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getResABNameBytes() {
      java.lang.Object ref = resABName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resABName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESSLTABNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object resSltABName_;
    /**
     * <code>optional string ResSltABName = 8;</code>
     */
    public java.lang.String getResSltABName() {
      java.lang.Object ref = resSltABName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resSltABName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResSltABName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getResSltABNameBytes() {
      java.lang.Object ref = resSltABName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resSltABName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESADDTIME_FIELD_NUMBER = 9;
    private volatile java.lang.Object resAddTime_;
    /**
     * <code>optional string ResAddTime = 9;</code>
     */
    public java.lang.String getResAddTime() {
      java.lang.Object ref = resAddTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resAddTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResAddTime = 9;</code>
     */
    public com.google.protobuf.ByteString
        getResAddTimeBytes() {
      java.lang.Object ref = resAddTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resAddTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESADDMAN_FIELD_NUMBER = 10;
    private volatile java.lang.Object resAddMan_;
    /**
     * <code>optional string ResAddMan = 10;</code>
     */
    public java.lang.String getResAddMan() {
      java.lang.Object ref = resAddMan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resAddMan_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResAddMan = 10;</code>
     */
    public com.google.protobuf.ByteString
        getResAddManBytes() {
      java.lang.Object ref = resAddMan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resAddMan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESUPTIME_FIELD_NUMBER = 11;
    private volatile java.lang.Object resUpTime_;
    /**
     * <code>optional string ResUpTime = 11;</code>
     */
    public java.lang.String getResUpTime() {
      java.lang.Object ref = resUpTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resUpTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResUpTime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getResUpTimeBytes() {
      java.lang.Object ref = resUpTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resUpTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESUPMAN_FIELD_NUMBER = 12;
    private volatile java.lang.Object resUpMan_;
    /**
     * <code>optional string ResUpMan = 12;</code>
     */
    public java.lang.String getResUpMan() {
      java.lang.Object ref = resUpMan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resUpMan_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResUpMan = 12;</code>
     */
    public com.google.protobuf.ByteString
        getResUpManBytes() {
      java.lang.Object ref = resUpMan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resUpMan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESMODEL_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString resModel_;
    /**
     * <code>optional bytes ResModel = 13;</code>
     */
    public com.google.protobuf.ByteString getResModel() {
      return resModel_;
    }

    public static final int RESPIC_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString resPic_;
    /**
     * <code>optional bytes ResPic = 14;</code>
     */
    public com.google.protobuf.ByteString getResPic() {
      return resPic_;
    }

    public static final int RESGUID_FIELD_NUMBER = 15;
    private volatile java.lang.Object resGuid_;
    /**
     * <code>optional string ResGuid = 15;</code>
     */
    public java.lang.String getResGuid() {
      java.lang.Object ref = resGuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resGuid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ResGuid = 15;</code>
     */
    public com.google.protobuf.ByteString
        getResGuidBytes() {
      java.lang.Object ref = resGuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resType_);
      }
      if (!getResNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resName_);
      }
      if (!getResCostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resCost_);
      }
      if (!getResUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, resUnit_);
      }
      if (!getResModelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resModelName_);
      }
      if (!getResPicNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, resPicName_);
      }
      if (!getResABNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, resABName_);
      }
      if (!getResSltABNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, resSltABName_);
      }
      if (!getResAddTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, resAddTime_);
      }
      if (!getResAddManBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, resAddMan_);
      }
      if (!getResUpTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, resUpTime_);
      }
      if (!getResUpManBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, resUpMan_);
      }
      if (!resModel_.isEmpty()) {
        output.writeBytes(13, resModel_);
      }
      if (!resPic_.isEmpty()) {
        output.writeBytes(14, resPic_);
      }
      if (!getResGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, resGuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resType_);
      }
      if (!getResNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resName_);
      }
      if (!getResCostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resCost_);
      }
      if (!getResUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, resUnit_);
      }
      if (!getResModelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resModelName_);
      }
      if (!getResPicNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, resPicName_);
      }
      if (!getResABNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, resABName_);
      }
      if (!getResSltABNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, resSltABName_);
      }
      if (!getResAddTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, resAddTime_);
      }
      if (!getResAddManBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, resAddMan_);
      }
      if (!getResUpTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, resUpTime_);
      }
      if (!getResUpManBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, resUpMan_);
      }
      if (!resModel_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, resModel_);
      }
      if (!resPic_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, resPic_);
      }
      if (!getResGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, resGuid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sgcc.bochao.ggt.manage.protobuf.ResData.Res)) {
        return super.equals(obj);
      }
      com.sgcc.bochao.ggt.manage.protobuf.ResData.Res other = (com.sgcc.bochao.ggt.manage.protobuf.ResData.Res) obj;

      boolean result = true;
      result = result && getResType()
          .equals(other.getResType());
      result = result && getResName()
          .equals(other.getResName());
      result = result && getResCost()
          .equals(other.getResCost());
      result = result && getResUnit()
          .equals(other.getResUnit());
      result = result && getResModelName()
          .equals(other.getResModelName());
      result = result && getResPicName()
          .equals(other.getResPicName());
      result = result && getResABName()
          .equals(other.getResABName());
      result = result && getResSltABName()
          .equals(other.getResSltABName());
      result = result && getResAddTime()
          .equals(other.getResAddTime());
      result = result && getResAddMan()
          .equals(other.getResAddMan());
      result = result && getResUpTime()
          .equals(other.getResUpTime());
      result = result && getResUpMan()
          .equals(other.getResUpMan());
      result = result && getResModel()
          .equals(other.getResModel());
      result = result && getResPic()
          .equals(other.getResPic());
      result = result && getResGuid()
          .equals(other.getResGuid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getResType().hashCode();
      hash = (37 * hash) + RESNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResName().hashCode();
      hash = (37 * hash) + RESCOST_FIELD_NUMBER;
      hash = (53 * hash) + getResCost().hashCode();
      hash = (37 * hash) + RESUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getResUnit().hashCode();
      hash = (37 * hash) + RESMODELNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResModelName().hashCode();
      hash = (37 * hash) + RESPICNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResPicName().hashCode();
      hash = (37 * hash) + RESABNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResABName().hashCode();
      hash = (37 * hash) + RESSLTABNAME_FIELD_NUMBER;
      hash = (53 * hash) + getResSltABName().hashCode();
      hash = (37 * hash) + RESADDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getResAddTime().hashCode();
      hash = (37 * hash) + RESADDMAN_FIELD_NUMBER;
      hash = (53 * hash) + getResAddMan().hashCode();
      hash = (37 * hash) + RESUPTIME_FIELD_NUMBER;
      hash = (53 * hash) + getResUpTime().hashCode();
      hash = (37 * hash) + RESUPMAN_FIELD_NUMBER;
      hash = (53 * hash) + getResUpMan().hashCode();
      hash = (37 * hash) + RESMODEL_FIELD_NUMBER;
      hash = (53 * hash) + getResModel().hashCode();
      hash = (37 * hash) + RESPIC_FIELD_NUMBER;
      hash = (53 * hash) + getResPic().hashCode();
      hash = (37 * hash) + RESGUID_FIELD_NUMBER;
      hash = (53 * hash) + getResGuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sgcc.bochao.ggt.manage.protobuf.ResData.Res prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Res)
        com.sgcc.bochao.ggt.manage.protobuf.ResData.ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_Res_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.class, com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.Builder.class);
      }

      // Construct using com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resType_ = "";

        resName_ = "";

        resCost_ = "";

        resUnit_ = "";

        resModelName_ = "";

        resPicName_ = "";

        resABName_ = "";

        resSltABName_ = "";

        resAddTime_ = "";

        resAddMan_ = "";

        resUpTime_ = "";

        resUpMan_ = "";

        resModel_ = com.google.protobuf.ByteString.EMPTY;

        resPic_ = com.google.protobuf.ByteString.EMPTY;

        resGuid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.internal_static_protobuf_Res_descriptor;
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getDefaultInstanceForType() {
        return com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.getDefaultInstance();
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res build() {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res buildPartial() {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.Res result = new com.sgcc.bochao.ggt.manage.protobuf.ResData.Res(this);
        result.resType_ = resType_;
        result.resName_ = resName_;
        result.resCost_ = resCost_;
        result.resUnit_ = resUnit_;
        result.resModelName_ = resModelName_;
        result.resPicName_ = resPicName_;
        result.resABName_ = resABName_;
        result.resSltABName_ = resSltABName_;
        result.resAddTime_ = resAddTime_;
        result.resAddMan_ = resAddMan_;
        result.resUpTime_ = resUpTime_;
        result.resUpMan_ = resUpMan_;
        result.resModel_ = resModel_;
        result.resPic_ = resPic_;
        result.resGuid_ = resGuid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sgcc.bochao.ggt.manage.protobuf.ResData.Res) {
          return mergeFrom((com.sgcc.bochao.ggt.manage.protobuf.ResData.Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sgcc.bochao.ggt.manage.protobuf.ResData.Res other) {
        if (other == com.sgcc.bochao.ggt.manage.protobuf.ResData.Res.getDefaultInstance()) return this;
        if (!other.getResType().isEmpty()) {
          resType_ = other.resType_;
          onChanged();
        }
        if (!other.getResName().isEmpty()) {
          resName_ = other.resName_;
          onChanged();
        }
        if (!other.getResCost().isEmpty()) {
          resCost_ = other.resCost_;
          onChanged();
        }
        if (!other.getResUnit().isEmpty()) {
          resUnit_ = other.resUnit_;
          onChanged();
        }
        if (!other.getResModelName().isEmpty()) {
          resModelName_ = other.resModelName_;
          onChanged();
        }
        if (!other.getResPicName().isEmpty()) {
          resPicName_ = other.resPicName_;
          onChanged();
        }
        if (!other.getResABName().isEmpty()) {
          resABName_ = other.resABName_;
          onChanged();
        }
        if (!other.getResSltABName().isEmpty()) {
          resSltABName_ = other.resSltABName_;
          onChanged();
        }
        if (!other.getResAddTime().isEmpty()) {
          resAddTime_ = other.resAddTime_;
          onChanged();
        }
        if (!other.getResAddMan().isEmpty()) {
          resAddMan_ = other.resAddMan_;
          onChanged();
        }
        if (!other.getResUpTime().isEmpty()) {
          resUpTime_ = other.resUpTime_;
          onChanged();
        }
        if (!other.getResUpMan().isEmpty()) {
          resUpMan_ = other.resUpMan_;
          onChanged();
        }
        if (other.getResModel() != com.google.protobuf.ByteString.EMPTY) {
          setResModel(other.getResModel());
        }
        if (other.getResPic() != com.google.protobuf.ByteString.EMPTY) {
          setResPic(other.getResPic());
        }
        if (!other.getResGuid().isEmpty()) {
          resGuid_ = other.resGuid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sgcc.bochao.ggt.manage.protobuf.ResData.Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sgcc.bochao.ggt.manage.protobuf.ResData.Res) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object resType_ = "";
      /**
       * <code>optional string ResType = 1;</code>
       */
      public java.lang.String getResType() {
        java.lang.Object ref = resType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResTypeBytes() {
        java.lang.Object ref = resType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResType = 1;</code>
       */
      public Builder setResType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResType = 1;</code>
       */
      public Builder clearResType() {
        
        resType_ = getDefaultInstance().getResType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResType = 1;</code>
       */
      public Builder setResTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resName_ = "";
      /**
       * <code>optional string ResName = 2;</code>
       */
      public java.lang.String getResName() {
        java.lang.Object ref = resName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResNameBytes() {
        java.lang.Object ref = resName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResName = 2;</code>
       */
      public Builder setResName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResName = 2;</code>
       */
      public Builder clearResName() {
        
        resName_ = getDefaultInstance().getResName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResName = 2;</code>
       */
      public Builder setResNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resCost_ = "";
      /**
       * <code>optional string ResCost = 3;</code>
       */
      public java.lang.String getResCost() {
        java.lang.Object ref = resCost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resCost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResCost = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResCostBytes() {
        java.lang.Object ref = resCost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resCost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResCost = 3;</code>
       */
      public Builder setResCost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResCost = 3;</code>
       */
      public Builder clearResCost() {
        
        resCost_ = getDefaultInstance().getResCost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResCost = 3;</code>
       */
      public Builder setResCostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resCost_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resUnit_ = "";
      /**
       * <code>optional string ResUnit = 4;</code>
       */
      public java.lang.String getResUnit() {
        java.lang.Object ref = resUnit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resUnit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResUnit = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResUnitBytes() {
        java.lang.Object ref = resUnit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resUnit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResUnit = 4;</code>
       */
      public Builder setResUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUnit = 4;</code>
       */
      public Builder clearResUnit() {
        
        resUnit_ = getDefaultInstance().getResUnit();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUnit = 4;</code>
       */
      public Builder setResUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resUnit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resModelName_ = "";
      /**
       * <code>optional string ResModelName = 5;</code>
       */
      public java.lang.String getResModelName() {
        java.lang.Object ref = resModelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resModelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResModelName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getResModelNameBytes() {
        java.lang.Object ref = resModelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resModelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResModelName = 5;</code>
       */
      public Builder setResModelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resModelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResModelName = 5;</code>
       */
      public Builder clearResModelName() {
        
        resModelName_ = getDefaultInstance().getResModelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResModelName = 5;</code>
       */
      public Builder setResModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resModelName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resPicName_ = "";
      /**
       * <code>optional string ResPicName = 6;</code>
       */
      public java.lang.String getResPicName() {
        java.lang.Object ref = resPicName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resPicName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResPicName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getResPicNameBytes() {
        java.lang.Object ref = resPicName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resPicName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResPicName = 6;</code>
       */
      public Builder setResPicName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resPicName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResPicName = 6;</code>
       */
      public Builder clearResPicName() {
        
        resPicName_ = getDefaultInstance().getResPicName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResPicName = 6;</code>
       */
      public Builder setResPicNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resPicName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resABName_ = "";
      /**
       * <code>optional string ResABName = 7;</code>
       */
      public java.lang.String getResABName() {
        java.lang.Object ref = resABName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resABName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResABName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getResABNameBytes() {
        java.lang.Object ref = resABName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resABName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResABName = 7;</code>
       */
      public Builder setResABName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resABName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResABName = 7;</code>
       */
      public Builder clearResABName() {
        
        resABName_ = getDefaultInstance().getResABName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResABName = 7;</code>
       */
      public Builder setResABNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resABName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resSltABName_ = "";
      /**
       * <code>optional string ResSltABName = 8;</code>
       */
      public java.lang.String getResSltABName() {
        java.lang.Object ref = resSltABName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resSltABName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResSltABName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getResSltABNameBytes() {
        java.lang.Object ref = resSltABName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resSltABName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResSltABName = 8;</code>
       */
      public Builder setResSltABName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resSltABName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResSltABName = 8;</code>
       */
      public Builder clearResSltABName() {
        
        resSltABName_ = getDefaultInstance().getResSltABName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResSltABName = 8;</code>
       */
      public Builder setResSltABNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resSltABName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resAddTime_ = "";
      /**
       * <code>optional string ResAddTime = 9;</code>
       */
      public java.lang.String getResAddTime() {
        java.lang.Object ref = resAddTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resAddTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResAddTime = 9;</code>
       */
      public com.google.protobuf.ByteString
          getResAddTimeBytes() {
        java.lang.Object ref = resAddTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resAddTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResAddTime = 9;</code>
       */
      public Builder setResAddTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resAddTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResAddTime = 9;</code>
       */
      public Builder clearResAddTime() {
        
        resAddTime_ = getDefaultInstance().getResAddTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResAddTime = 9;</code>
       */
      public Builder setResAddTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resAddTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resAddMan_ = "";
      /**
       * <code>optional string ResAddMan = 10;</code>
       */
      public java.lang.String getResAddMan() {
        java.lang.Object ref = resAddMan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resAddMan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResAddMan = 10;</code>
       */
      public com.google.protobuf.ByteString
          getResAddManBytes() {
        java.lang.Object ref = resAddMan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resAddMan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResAddMan = 10;</code>
       */
      public Builder setResAddMan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resAddMan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResAddMan = 10;</code>
       */
      public Builder clearResAddMan() {
        
        resAddMan_ = getDefaultInstance().getResAddMan();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResAddMan = 10;</code>
       */
      public Builder setResAddManBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resAddMan_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resUpTime_ = "";
      /**
       * <code>optional string ResUpTime = 11;</code>
       */
      public java.lang.String getResUpTime() {
        java.lang.Object ref = resUpTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resUpTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResUpTime = 11;</code>
       */
      public com.google.protobuf.ByteString
          getResUpTimeBytes() {
        java.lang.Object ref = resUpTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resUpTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResUpTime = 11;</code>
       */
      public Builder setResUpTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resUpTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUpTime = 11;</code>
       */
      public Builder clearResUpTime() {
        
        resUpTime_ = getDefaultInstance().getResUpTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUpTime = 11;</code>
       */
      public Builder setResUpTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resUpTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resUpMan_ = "";
      /**
       * <code>optional string ResUpMan = 12;</code>
       */
      public java.lang.String getResUpMan() {
        java.lang.Object ref = resUpMan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resUpMan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResUpMan = 12;</code>
       */
      public com.google.protobuf.ByteString
          getResUpManBytes() {
        java.lang.Object ref = resUpMan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resUpMan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResUpMan = 12;</code>
       */
      public Builder setResUpMan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resUpMan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUpMan = 12;</code>
       */
      public Builder clearResUpMan() {
        
        resUpMan_ = getDefaultInstance().getResUpMan();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResUpMan = 12;</code>
       */
      public Builder setResUpManBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resUpMan_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString resModel_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ResModel = 13;</code>
       */
      public com.google.protobuf.ByteString getResModel() {
        return resModel_;
      }
      /**
       * <code>optional bytes ResModel = 13;</code>
       */
      public Builder setResModel(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ResModel = 13;</code>
       */
      public Builder clearResModel() {
        
        resModel_ = getDefaultInstance().getResModel();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString resPic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ResPic = 14;</code>
       */
      public com.google.protobuf.ByteString getResPic() {
        return resPic_;
      }
      /**
       * <code>optional bytes ResPic = 14;</code>
       */
      public Builder setResPic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resPic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ResPic = 14;</code>
       */
      public Builder clearResPic() {
        
        resPic_ = getDefaultInstance().getResPic();
        onChanged();
        return this;
      }

      private java.lang.Object resGuid_ = "";
      /**
       * <code>optional string ResGuid = 15;</code>
       */
      public java.lang.String getResGuid() {
        java.lang.Object ref = resGuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resGuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResGuid = 15;</code>
       */
      public com.google.protobuf.ByteString
          getResGuidBytes() {
        java.lang.Object ref = resGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResGuid = 15;</code>
       */
      public Builder setResGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResGuid = 15;</code>
       */
      public Builder clearResGuid() {
        
        resGuid_ = getDefaultInstance().getResGuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResGuid = 15;</code>
       */
      public Builder setResGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resGuid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Res)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Res)
    private static final com.sgcc.bochao.ggt.manage.protobuf.ResData.Res DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sgcc.bochao.ggt.manage.protobuf.ResData.Res();
    }

    public static com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Res>
        PARSER = new com.google.protobuf.AbstractParser<Res>() {
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Res(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Res> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    public com.sgcc.bochao.ggt.manage.protobuf.ResData.Res getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ResSSS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ResSSS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Res_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rResData.proto\022\010protobuf\"$\n\006ResSSS\022\032\n\003r" +
      "es\030\001 \003(\0132\r.protobuf.Res\"\233\002\n\003Res\022\017\n\007ResTy" +
      "pe\030\001 \001(\t\022\017\n\007ResName\030\002 \001(\t\022\017\n\007ResCost\030\003 \001" +
      "(\t\022\017\n\007ResUnit\030\004 \001(\t\022\024\n\014ResModelName\030\005 \001(" +
      "\t\022\022\n\nResPicName\030\006 \001(\t\022\021\n\tResABName\030\007 \001(\t" +
      "\022\024\n\014ResSltABName\030\010 \001(\t\022\022\n\nResAddTime\030\t \001" +
      "(\t\022\021\n\tResAddMan\030\n \001(\t\022\021\n\tResUpTime\030\013 \001(\t" +
      "\022\020\n\010ResUpMan\030\014 \001(\t\022\020\n\010ResModel\030\r \001(\014\022\016\n\006" +
      "ResPic\030\016 \001(\014\022\017\n\007ResGuid\030\017 \001(\tB.\n#com.sgc" +
      "c.bochao.ggt.manage.protobufB\007ResDatab\006p",
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_ResSSS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ResSSS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ResSSS_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_protobuf_Res_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Res_descriptor,
        new java.lang.String[] { "ResType", "ResName", "ResCost", "ResUnit", "ResModelName", "ResPicName", "ResABName", "ResSltABName", "ResAddTime", "ResAddMan", "ResUpTime", "ResUpMan", "ResModel", "ResPic", "ResGuid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
